name: OpenSSL Conan Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM
  workflow_dispatch:

env:
  CONAN_CPU_COUNT: 4
  OSSL_RUN_CI_TESTS: "1"

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        conan-dev/venv/bin/python -m pip install --upgrade pip
        pip install conan==2.* PyYAML pytest requests

    - name: Run comprehensive tests
      run: |
        conan-dev/venv/bin/python scripts/conan/test_harness.py --test-suite all --results-dir nightly_test_results

    - name: Run performance benchmarks
      run: |
        conan-dev/venv/bin/python scripts/conan/performance_benchmark.py --results-dir nightly_performance_results --verbose

    - name: Generate nightly report
      run: |
        conan-dev/venv/bin/python -c "
        import json
        from datetime import datetime
        
        report = {
            'timestamp': datetime.now().isoformat(),
            'type': 'nightly',
            'status': 'completed',
            'tests': 'nightly_test_results/',
            'performance': 'nightly_performance_results/'
        }
        
        with open('nightly_report.json', 'w') as f:
            json.dump(report, f, indent=2)
        "

    - name: Upload nightly results
      uses: actions/upload-artifact@v4
      with:
        name: nightly-results-${{ github.run_number }}
        path: |
          nightly_test_results/
          nightly_performance_results/
          nightly_report.json
        retention-days: 30

    - name: Notify completion
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: '🌙 OpenSSL Conan nightly build completed successfully!'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        fields: repo,message,commit,author,action,eventName,ref,workflow