name: Python Environment Package

on:
  push:
    branches: [main, master]
    paths:
      - 'scripts/setup-ci-environment.py'
      - 'scripts/openssl_conan/**'
      - 'conan-dev/**'
      - 'requirements.txt'
      - 'pyproject.toml'
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to package'
        required: true
        default: '3.12'
      package_version:
        description: 'Package version'
        required: true
        default: 'auto'

env:
  CONAN_USER_HOME: ${{ github.workspace }}/.conan2
  CONAN_COLOR_DISPLAY: 1
  CLICOLOR_FORCE: 1
  CLICOLOR: 1

jobs:
  prepare-package:
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.version.outputs.python_version }}
      package_version: ${{ steps.version.outputs.package_version }}
      should_package: ${{ steps.version.outputs.should_package }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Determine package version
        id: version
        run: |
          if [ "${{ github.event.inputs.package_version }}" = "auto" ]; then
            # Generate version based on date and commit
            DATE=$(date +%Y%m%d)
            SHORT_SHA=$(git rev-parse --short HEAD)
            PACKAGE_VERSION="${DATE}.${SHORT_SHA}"
          else
            PACKAGE_VERSION="${{ github.event.inputs.package_version }}"
          fi
          
          PYTHON_VERSION="${{ github.event.inputs.python_version || '3.12' }}"
          
          # Check if this version already exists
          if git tag | grep -q "^python-env-$PACKAGE_VERSION$"; then
            echo "should_package=false" >> $GITHUB_OUTPUT
          else
            echo "should_package=true" >> $GITHUB_OUTPUT
          fi
          
          echo "python_version=$PYTHON_VERSION" >> $GITHUB_OUTPUT
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "Python version: $PYTHON_VERSION"
          echo "Package version: $PACKAGE_VERSION"
          echo "Should package: ${{ steps.version.outputs.should_package }}"

  build-python-environment:
    needs: prepare-package
    if: needs.prepare-package.outputs.should_package == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            profile: linux-gcc11
            platform: linux
          - os: windows-2022
            profile: windows-msvc2022
            platform: windows
          - os: macos-12
            profile: macos-clang14
            platform: macos
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ needs.prepare-package.outputs.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ needs.prepare-package.outputs.python_version }}
          cache: 'pip'
      
      - name: Set up Conan Python Environment
        run: |
          python scripts/setup-ci-environment.py
      
      - name: Install Conan
        run: |
          pip install conan>=2.0.0
          conan profile detect --force
      
      - name: Create Python Environment Package Recipe
        run: |
          cat > python-environment-conanfile.py << 'EOF'
          from conan import ConanFile
          from conan.tools.files import copy, save
          from conan.tools.cmake import CMake, CMakeToolchain, CMakeDeps
          import os
          import sys
          from pathlib import Path
          
          class PythonEnvironmentConan(ConanFile):
              name = "openssl-python-environment"
              version = "${{ needs.prepare-package.outputs.package_version }}"
              description = "OpenSSL Python development environment with Conan tools"
              license = "Apache-2.0"
              url = "https://github.com/openssl/openssl"
              homepage = "https://www.openssl.org"
              topics = ("openssl", "python", "conan", "development", "environment")
              
              settings = "os", "arch", "compiler", "build_type"
              options = {
                  "python_version": ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"],
                  "include_dev_tools": [True, False],
                  "include_testing": [True, False],
              }
              default_options = {
                  "python_version": "${{ needs.prepare-package.outputs.python_version }}",
                  "include_dev_tools": True,
                  "include_testing": True,
              }
              
              def requirements(self):
                  self.requires("openssl/3.5.0")
                  
              def build_requirements(self):
                  if self.options.include_dev_tools:
                      self.tool_requires("cmake/[>=3.15]")
                      self.tool_requires("ninja/[>=1.10]")
                      self.tool_requires("pkgconf/[>=1.7]")
                  
              def generate(self):
                  # Create Python environment setup script
                  python_setup = f'''#!/usr/bin/env python{self.options.python_version}
          """
          OpenSSL Python Environment Setup
          Generated by Conan package openssl-python-environment/{self.version}
          """
          
          import os
          import sys
          import subprocess
          from pathlib import Path
          
          def setup_environment():
              """Set up the OpenSSL Python development environment."""
              print("🐍 Setting up OpenSSL Python environment...")
              
              # Get the package directory
              package_dir = Path(__file__).parent
              python_exe = sys.executable
              
              # Install required packages
              requirements = [
                  "conan>=2.0.0",
                  "PyYAML",
                  "pytest",
                  "pytest-cov",
                  "coverage",
                  "black",
                  "flake8",
                  "pylint",
                  "mypy",
                  "isort",
                  "markdown-it",
                  "normalizer",
                  "distro"
              ]
              
              if {str(self.options.include_testing).lower()}:
                  requirements.extend([
                      "pytest-xdist",
                      "pytest-mock",
                      "pytest-benchmark"
                  ])
              
              for package in requirements:
                  try:
                      subprocess.run([python_exe, "-m", "pip", "install", package], 
                                   check=True, capture_output=True)
                      print(f"✅ Installed {{package}}")
                  except subprocess.CalledProcessError as e:
                      print(f"⚠️  Warning: Failed to install {{package}}: {{e}}")
              
              # Set up environment variables
              os.environ['PYTHON_APPLICATION'] = python_exe
              os.environ['CONAN_COLOR_DISPLAY'] = '1'
              os.environ['CLICOLOR_FORCE'] = '1'
              os.environ['CLICOLOR'] = '1'
              
              print("✅ OpenSSL Python environment setup complete!")
              print(f"Python executable: {{python_exe}}")
              print(f"Package version: {self.version}")
          
          if __name__ == "__main__":
              setup_environment()
          '''
                  
                  # Save the setup script
                  save(self, "bin/setup_environment.py", python_setup)
                  
                  # Create a simple README
                  readme = f'''# OpenSSL Python Environment {self.version}
          
          This package provides a complete Python development environment for OpenSSL development with Conan integration.
          
          ## Features
          - Python {self.options.python_version}
          - Conan package manager
          - Development tools: black, flake8, pylint, mypy, isort
          - Testing tools: pytest, pytest-cov, coverage
          - OpenSSL integration scripts
          
          ## Usage
          
          After installing this package, run:
          ```bash
          python bin/setup_environment.py
          ```
          
          This will set up your Python environment with all required tools.
          
          ## Platform
          - OS: {self.settings.os}
          - Architecture: {self.settings.arch}
          - Compiler: {self.settings.compiler}
          - Build Type: {self.settings.build_type}
          '''
                  
                  save(self, "README.md", readme)
                  
                  # Create a requirements.txt
                  requirements_txt = f'''# OpenSSL Python Environment Requirements
          # Generated by openssl-python-environment/{self.version}
          
          conan>=2.0.0
          PyYAML
          pytest
          pytest-cov
          coverage
          black
          flake8
          pylint
          mypy
          isort
          markdown-it
          normalizer
          distro
          '''
                  
                  if self.options.include_testing:
                      requirements_txt += '''
          pytest-xdist
          pytest-mock
          pytest-benchmark
          '''
                  
                  save(self, "requirements.txt", requirements_txt)
          
          def package(self):
              # Copy the generated files
              copy(self, "bin/setup_environment.py", self.build_folder, "bin")
              copy(self, "README.md", self.build_folder, ".")
              copy(self, "requirements.txt", self.build_folder, ".")
              
              # Copy OpenSSL Conan scripts
              copy(self, "scripts/openssl_conan/**", self.build_folder, "scripts/openssl_conan")
              
              # Copy Conan profiles
              copy(self, "conan-dev/profiles/**", self.build_folder, "conan-dev/profiles")
          
          def package_info(self):
              self.cpp_info.libs = []
              self.cpp_info.includedirs = []
              self.cpp_info.libdirs = []
              
              # Set environment variables
              self.runenv_info.define("PYTHON_APPLICATION", sys.executable)
              self.runenv_info.define("CONAN_COLOR_DISPLAY", "1")
              self.runenv_info.define("CLICOLOR_FORCE", "1")
              self.runenv_info.define("CLICOLOR", "1")
          EOF
      
      - name: Build Python Environment Package
        run: |
          conan create python-environment-conanfile.py --profile=conan-dev/profiles/${{ matrix.profile }}.profile --build=missing
      
      - name: Upload to Conan Center
        run: |
          conan upload "openssl-python-environment/${{ needs.prepare-package.outputs.package_version }}@openssl/stable" --all --confirm
      
      - name: Upload to Artifactory (if configured)
        if: env.ARTIFACTORY_URL != ''
        run: |
          conan remote add artifactory ${{ env.ARTIFACTORY_URL }}
          conan user -p ${{ secrets.ARTIFACTORY_PASSWORD }} -r artifactory ${{ secrets.ARTIFACTORY_USERNAME }}
          conan upload "openssl-python-environment/${{ needs.prepare-package.outputs.package_version }}@openssl/stable" -r=artifactory --all --confirm
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-env-${{ matrix.platform }}-${{ needs.prepare-package.outputs.package_version }}
          path: |
            ~/.conan2/p/*/p/
            python-environment-conanfile.py

  create-release:
    needs: [prepare-package, build-python-environment]
    if: needs.prepare-package.outputs.should_package == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install Conan
        run: |
          pip install conan>=2.0.0
          conan profile detect --force
      
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: python-env-${{ needs.prepare-package.outputs.package_version }}
          release_name: OpenSSL Python Environment ${{ needs.prepare-package.outputs.package_version }}
          body: |
            OpenSSL Python Environment ${{ needs.prepare-package.outputs.package_version }}
            
            A complete Python development environment for OpenSSL development with Conan integration.
            
            ## Features
            - Python ${{ needs.prepare-package.outputs.python_version }}
            - Conan package manager
            - Development tools: black, flake8, pylint, mypy, isort
            - Testing tools: pytest, pytest-cov, coverage
            - OpenSSL integration scripts
            - Cross-platform support (Linux, Windows, macOS)
            
            ## Installation
            ```bash
            conan install openssl-python-environment/${{ needs.prepare-package.outputs.package_version }}@openssl/stable
            ```
            
            ## Usage
            After installation, run:
            ```bash
            python bin/setup_environment.py
            ```
            
            This will set up your Python environment with all required tools for OpenSSL development.
          draft: false
          prerelease: false