# Generated by configure.py
# Do not edit manually

package configdata;

our %config = (
    'shared' => True,
    'static' => True,
    'threads' => True,
    'asm' => True,
    'fips' => False,
    'no_shared' => False,
    'no_static' => False,
    'no_threads' => False,
    'no_asm' => False,
    'enable_fips' => False,
);

our $target = 'linux-x86_64';

our %defines = (
);

1;
