
# Generated by configure.py
# Do not edit manually

PLATFORM = linux-x86_64
CONFIG = shared=True static=True threads=True asm=True fips=False no_shared=False no_static=False no_threads=False no_asm=False enable_fips=False
DEFINES = 
INCLUDES = 
LIBDIRS = 
LIBS = 

all: build

build:
	@echo "Building OpenSSL..."
	# Build commands would go here

clean:
	@echo "Cleaning..."
	# Clean commands would go here

install:
	@echo "Installing..."
	# Install commands would go here

.PHONY: all build clean install
