name: OpenSSL Conan PR Tests

on:
  pull_request:
    branches: [ develop, main ]
    paths:
      - 'conanfile.py'
      - 'scripts/**'
      - '.github/workflows/**'
      - 'VERSION.dat'

env:
  CONAN_CPU_COUNT: 2
  OSSL_RUN_CI_TESTS: "1"
  CONAN_USER_HOME: ${{ github.workspace }}/.conan2
  CONAN_COLOR_DISPLAY: 1
  CLICOLOR_FORCE: 1
  CLICOLOR: 1

jobs:
  # Quick validation for PRs
  pr-validation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Conan install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install conan==2.* PyYAML pytest

    - name: Validate conanfile.py
      run: |
        python -c "from conanfile import OpenSSLConan; print('✅ conanfile.py is valid')"

    - name: Run basic tests
      run: |
        python scripts/conan/test_harness.py --test-suite basic --results-dir pr_test_results

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pr-test-results
        path: pr_test_results/

  # Build matrix for different configurations
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [linux-gcc11, linux-clang15]
        build_type: [Debug, Release]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Conan install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install conan==2.* PyYAML pytest

    - name: Conan build
      run: |
        conan install . --profile=conan-dev/profiles/${{ matrix.profile }}.profile --build=missing
        conan build . --profile=conan-dev/profiles/${{ matrix.profile }}.profile

    - name: Conan test
      run: |
        conan test . --profile=conan-dev/profiles/${{ matrix.profile }}.profile

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-artifacts-${{ matrix.profile }}-${{ matrix.build_type }}
        path: build/