# Copyright 2021-2024 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: CIFuzz
on:
  # Only run on main branch pushes and when specifically requested
  push:
    branches: [ main, master ]
  pull_request:
    paths:
      - 'fuzz/**'
      - '.github/workflows/main.yml'
  schedule:
    # Run weekly on Sundays
    - cron: '0 6 * * 0'
  workflow_dispatch:
    inputs:
      fuzz-seconds:
        description: 'Duration to run fuzzers (seconds)'
        required: false
        default: '300'
        type: string

permissions:
  contents: read

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'openssl'
        dry-run: false
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'openssl'
        fuzz-seconds: ${{ github.event.inputs.fuzz-seconds || '300' }}
        dry-run: false
    - name: Upload Crash
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cifuzz-artifacts
        path: ./out/artifacts
