version: '3.8'

services:
  ubuntu-20-04-gcc:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu-builder
      args:
        UBUNTU_VERSION: "20.04"
        COMPILER: "gcc-11"
        BUILD_TYPE: "Release"
        ENABLE_FIPS: "ON"
      target: artifacts
    volumes:
      - ../artifacts/ubuntu-20.04-gcc:/artifacts
    environment:
      - PLATFORM=ubuntu-20.04
      - COMPILER=gcc-11
      - ARCH=x86_64

  ubuntu-22-04-clang:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ubuntu-builder  
      args:
        UBUNTU_VERSION: "22.04"
        COMPILER: "clang-14"
        BUILD_TYPE: "Release"
        ENABLE_FIPS: "ON"
      target: artifacts
    volumes:
      - ../artifacts/ubuntu-22.04-clang:/artifacts
    environment:
      - PLATFORM=ubuntu-22.04
      - COMPILER=clang-14
      - ARCH=x86_64

  windows-2022:
    build:
      context: ..
      dockerfile: docker/Dockerfile.windows-builder
      args:
        WINDOWS_VERSION: "ltsc2022"
        BUILD_TYPE: "Release"
        ENABLE_FIPS: "ON"
      target: artifacts
    volumes:
      - ../artifacts/windows-2022:/artifacts
    environment:
      - PLATFORM=windows-2022
      - COMPILER=msvc193
      - ARCH=x86_64

  macos-x86_64:
    build:
      context: ..
      dockerfile: docker/Dockerfile.macos-builder
      args:
        BUILD_TYPE: "Release"
        TARGET_ARCH: "x86_64"
      target: artifacts
    volumes:
      - ../artifacts/macos-x86_64:/artifacts
    environment:
      - PLATFORM=macos
      - COMPILER=clang
      - ARCH=x86_64

  macos-arm64:
    build:
      context: ..
      dockerfile: docker/Dockerfile.macos-builder
      args:
        BUILD_TYPE: "Release"
        TARGET_ARCH: "arm64"
      target: artifacts
    volumes:
      - ../artifacts/macos-arm64:/artifacts
    environment:
      - PLATFORM=macos
      - COMPILER=clang
      - ARCH=arm64