build:
  build_dir: build
  install_dir: install
  jobs: '1'
  source_dir: .
conan:
  password: ''
  remote_name: openssl-conan-remote
  remote_url: https://your-artifactory-instance/artifactory/api/conan/openssl-conan
  user: ''
deployment:
  docker_image_name: openssl-conan-package
  target_registry: your-docker-registry.io/openssl
tests:
  performance_test_output: performance_report.json
  results_dir: test_results
  unit_test_command: pytest
