name: Basic Integration Test

on:
  push:
    branches: [ main, master ]
    paths:
      - 'conanfile.py'
      - 'scripts/**'
      - 'conan/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'conanfile.py'
      - 'scripts/**'
      - 'conan/**'
  workflow_dispatch:

jobs:
  basic-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout openssl-tools
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install Conan
        run: |
          pip install conan>=2.0
          conan --version
      
      - name: Validate conanfile.py syntax
        run: |
          echo "🔍 Validating conanfile.py syntax..."
          python3 -c "
          import sys
          sys.path.insert(0, '.')
          try:
              from conanfile import OpenSSLConan
              print('✅ conanfile.py imports successfully')
              
              # Test basic instantiation
              conan = OpenSSLConan()
              print('✅ OpenSSLConan class instantiated')
              
              # Test basic attributes
              assert hasattr(conan, 'name')
              assert hasattr(conan, 'version')
              assert hasattr(conan, 'options')
              print('✅ Basic class structure is valid')
              
          except Exception as e:
              print(f'❌ Validation failed: {e}')
              sys.exit(1)
          "
      
      - name: Test Conan configuration
        run: |
          echo "🔧 Testing Conan configuration..."
          conan profile detect --force
          conan config init
          conan config set general.revisions_enabled=1
          conan profile show default
      
      - name: Validate scripts directory
        run: |
          echo "📁 Validating scripts directory structure..."
          if [ -d "scripts" ]; then
            echo "✅ scripts directory exists"
            ls -la scripts/ | head -10
          else
            echo "❌ scripts directory missing"
            exit 1
          fi
      
      - name: Test basic Python imports
        run: |
          echo "🐍 Testing basic Python imports..."
          python3 -c "
          import sys
          sys.path.insert(0, '.')
          
          # Test core modules
          try:
              from util.custom_logging import setup_logging_from_config
              print('✅ util.custom_logging imports successfully')
          except ImportError as e:
              print(f'❌ util.custom_logging import failed: {e}')
              sys.exit(1)
              
          try:
              from conan.conan_functions import get_default_conan
              print('✅ conan.conan_functions imports successfully')
          except ImportError as e:
              print(f'❌ conan.conan_functions import failed: {e}')
              sys.exit(1)
          "
      
      - name: Integration test summary
        run: |
          echo "🎉 Basic integration test completed successfully!"
          echo "✅ Repository structure is valid"
          echo "✅ Python modules can be imported"
          echo "✅ Conan configuration works"
          echo "✅ Ready for advanced integration testing"
