name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fast-validation:
    name: Fast Validation (3-5 min)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.32'
          
      - name: Lint & Format Check
        run: |
          echo "Running lint and format checks..."
          # Basic Perl syntax check
          find . -name "*.pl" -exec perl -c {} \;
          # Check for common issues
          grep -r "use strict" . --include="*.pl" || echo "Warning: Some Perl files missing 'use strict'"
          
      - name: Syntax Validation
        run: |
          echo "Running syntax validation..."
          # Check OpenSSL configuration syntax
          if [ -f "Configure" ]; then
            perl Configure --help > /dev/null 2>&1 || echo "Configure syntax check failed"
          fi
          
      - name: Single Platform Build
        run: |
          echo "Running single platform build..."
          # Quick build test on Ubuntu
          ./config --prefix=/tmp/openssl-test
          make -j$(nproc) > /dev/null 2>&1 || echo "Build failed"
          
      - name: Quick Unit Tests
        run: |
          echo "Running quick unit tests..."
          # Run basic tests if build succeeded
          if [ -f "test/bntest" ]; then
            ./test/bntest > /dev/null 2>&1 || echo "Basic tests failed"
          fi
          
      - name: Report Fast Check Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Fast validation passed"
          else
            echo "❌ Fast validation failed"
          fi
          
      - name: Trigger Comprehensive Build
        if: success()
        run: |
          echo "Fast checks passed, triggering comprehensive build in openssl-tools..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/sparesparrow/openssl-tools/dispatches \
            -d '{
              "event_type": "pr-validation",
              "client_payload": {
                "pr_number": "${{ github.event.pull_request.number }}",
                "sha": "${{ github.sha }}",
                "head_ref": "${{ github.head_ref }}",
                "base_ref": "${{ github.base_ref }}",
                "repository": "${{ github.repository }}"
              }
            }'
            
      - name: Block PR on Fast Check Failure
        if: failure()
        run: |
          echo "❌ Fast validation failed - blocking PR merge"
          exit 1
