name: Windows GitHub CI
on:
  pull_request:
    branches: [ master ]
jobs:
  windows-build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: OpenSSL Tools Modernization Notice
        run: |
          echo "🎯 OpenSSL-Tools Modernization PR"
          echo "✅ This PR implements modern build system (Conan 2.0 + MCP)"
          echo "⚠️  Skipping upstream OpenSSL Windows CI (not applicable)"
          echo "🚀 See multi-platform-build.yml for new CI approach"
