# CI/CD Configuration
# This file configures the CI/CD workflows

# Build matrix
profiles:
  - linux-gcc11
  - linux-clang15
  - windows-msvc2022
  - macos-clang14

# Test configuration
test:
  coverage_threshold: 80
  timeout: 300

# Security scanning
security:
  enabled: true
  tools:
    - safety
    - bandit
    - semgrep

# Performance testing
performance:
  enabled: true
  benchmarks:
    - crypto_operations
    - memory_usage
    - build_time

# Release configuration
release:
  auto_tag: true
  create_github_release: true
  upload_to_remote: true