# Pre-build validation configuration for OpenSSL Conan packages

environment:
  # Required tools for building
  required_tools:
    - conan
    - python
    - git
    - make
    - gcc
    - g++
    - cmake
    - perl
  
  # Minimum version requirements
  min_conan_version: "2.0.0"
  min_python_version: "3.8"
  
  # Required environment variables
  required_env_vars:
    - CONAN_USER_HOME
    - CONAN_COLOR_DISPLAY
    - CLICOLOR_FORCE
  
  # Disk space requirements (in GB)
  disk_space_gb: 10
  
  # Memory requirements (in GB)
  min_memory_gb: 4

dependencies:
  # Check system packages
  check_system_packages: true
  
  # Required system packages (platform-specific)
  required_system_packages:
    linux:
      - build-essential
      - perl
      - pkg-config
      - libssl-dev
      - zlib1g-dev
    macos:
      - gcc
      - make
      - perl
      - pkg-config
    windows:
      - visual-studio
      - perl
      - nasm
  
  # Check Conan remotes
  check_conan_remotes: true
  
  # Required Conan remotes
  required_remotes:
    - conancenter
    - artifactory
    - github-packages
  
  # Check for required Conan packages
  check_conan_packages: true
  
  # Required Conan packages
  required_conan_packages:
    - zlib/1.3.1
    - openssl-tools/0.1.0

configuration:
  # Validate conanfile.py
  validate_conanfile: true
  
  # Check version consistency
  check_version_consistency: true
  
  # Validate Conan profiles
  validate_profiles: true
  
  # Check cache configuration
  check_cache_config: true
  
  # Validate build options
  validate_build_options: true
  
  # Check for required files
  check_required_files: true
  
  # Required files
  required_files:
    - conanfile.py
    - VERSION.dat
    - LICENSE.txt
    - README.md
    - configure
    - config

security:
  # Check for exposed secrets
  check_secrets: true
  
  # Validate SSL certificates
  validate_ssl_certs: true
  
  # Check file permissions
  check_file_permissions: true
  
  # Check for security vulnerabilities
  check_vulnerabilities: false  # Requires external tools
  
  # Validate package signatures
  validate_signatures: false  # Requires signing keys

cache:
  # Validate cache configuration
  validate_cache_config: true
  
  # Check cache directory permissions
  check_cache_permissions: true
  
  # Validate cache optimization settings
  validate_optimization: true
  
  # Check cache size limits
  check_cache_size: true
  
  # Maximum cache size (in GB)
  max_cache_size_gb: 50

build:
  # Validate build environment
  validate_build_env: true
  
  # Check compiler availability
  check_compilers: true
  
  # Validate build tools
  validate_build_tools: true
  
  # Check for required libraries
  check_libraries: true
  
  # Required libraries
  required_libraries:
    - libssl
    - libcrypto
    - libz

performance:
  # Check system performance
  check_performance: true
  
  # Minimum CPU cores
  min_cpu_cores: 2
  
  # Check available memory
  check_memory: true
  
  # Check disk I/O performance
  check_disk_io: false  # Requires specific tools

ci_cd:
  # Check CI/CD environment
  check_ci_env: true
  
  # Validate GitHub Actions
  validate_github_actions: true
  
  # Check for required secrets
  check_required_secrets: true
  
  # Required secrets
  required_secrets:
    - GITHUB_TOKEN
    - ARTIFACTORY_URL
    - ARTIFACTORY_USERNAME
    - ARTIFACTORY_PASSWORD

monitoring:
  # Enable monitoring
  enabled: true
  
  # Log validation results
  log_results: true
  
  # Generate validation report
  generate_report: true
  
  # Report format
  report_format: "json"  # json, yaml, text
  
  # Report location
  report_location: "validation-results.json"

# Validation rules
rules:
  # Strict mode - treat warnings as errors
  strict_mode: false
  
  # Fail on missing tools
  fail_on_missing_tools: true
  
  # Fail on missing dependencies
  fail_on_missing_deps: true
  
  # Fail on configuration errors
  fail_on_config_errors: true
  
  # Fail on security issues
  fail_on_security_issues: true
  
  # Allow partial validation
  allow_partial: false

# Custom validation checks
custom_checks:
  # Enable custom checks
  enabled: false
  
  # Custom check scripts
  scripts: []
  
  # Custom check timeout (seconds)
  timeout: 300

# Validation output
output:
  # Verbose output
  verbose: true
  
  # Color output
  color: true
  
  # Progress indicators
  progress: true
  
  # Summary format
  summary_format: "table"  # table, list, json
