/*
 * Generated build information
 * Do not edit manually - generated by mkbuildinf.py
 */

#ifndef OPENSSL_BUILDINFO_H
#define OPENSSL_BUILDINFO_H

#define OPENSSL_BUILDINFO_ARCHITECTURE "x86_64"
#define OPENSSL_BUILDINFO_BUILD_HOST "studio"
#define OPENSSL_BUILDINFO_BUILD_USER "sparrow"
#define OPENSSL_BUILDINFO_COMPILER "gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0"
#define OPENSSL_BUILDINFO_DATE "2025-10-26 13:33:06"
#define OPENSSL_BUILDINFO_GIT_COMMIT "1248d63f"
#define OPENSSL_BUILDINFO_PLATFORM "Linux-6.8.0-86-generic-x86_64-with-glibc2.39"
#define OPENSSL_BUILDINFO_PYTHON_VERSION "3.12.3"
#define OPENSSL_BUILDINFO_YEAR "2025"

#endif /* OPENSSL_BUILDINFO_H */
