name: Consolidated CI Simple

concurrency:
  group: openssl-ci-simple-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main, master, develop, simplify-openssl-build ]
  pull_request:
    branches: [ main, master, develop, simplify-openssl-build ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test
        run: |
          echo "✅ Consolidated CI Simple - Success"
          echo "Workflow: ${{ github.workflow }}"
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Time: $(date)"