# Minimal CI - Working Baseline
# This replaces the problematic baseline-ci.yml with correct paths and simplified approach
name: Minimal CI

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: 'Force run this workflow'
        required: false
        default: 'false'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'conanfile.py'
      - 'scripts/setup-ci-environment.py'
      - '.github/workflows/minimal-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CONAN_VERSION: "2.21.0"
  PYTHON_VERSION: "3.11"

jobs:
  minimal-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan==${{ env.CONAN_VERSION }}
          conan --version
      
      - name: Setup CI environment
        run: |
          if [ -f "scripts/setup-ci-environment.py" ]; then
            python scripts/setup-ci-environment.py
          else
            echo "setup-ci-environment.py not found, using defaults"
            conan profile detect --force
          fi
      
      - name: Verify Conan setup
        run: |
          conan profile show default || conan profile detect --force
          conan --version
          echo "Minimal CI test completed successfully"
      
      - name: Test conanfile.py (if exists)
        run: |
          if [ -f "conanfile.py" ]; then
            echo "Found conanfile.py, attempting basic validation"
            python -c "
import sys
sys.path.insert(0, '.')
try:
    from conanfile import *
    print('✓ conanfile.py syntax is valid')
except Exception as e:
    print(f'✗ conanfile.py has issues: {e}')
    sys.exit(1)
"
          else
            echo "No conanfile.py found, skipping validation"
          fi