name: Minimal Success

on:
  workflow_dispatch:
  push:
    branches: [ simplify-openssl-build ]

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: echo "✅ Success"