name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fast-validation:
    name: Fast Validation (3-5 min)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Conan
        run: |
          pip install "conan>=2.0,<3.0"
          conan --version
          
      - name: Basic Python Syntax Check
        run: |
          echo "Running Python syntax checks..."
          # Check all Python files for syntax errors
          find . -name "*.py" -exec python3 -m py_compile {} \;
          echo "✅ Python syntax validation passed"
          
      - name: Conanfile Validation
        run: |
          echo "Validating conanfile.py..."
          python3 -c "
          try:
              from conanfile import OpenSSLConan
              conan = OpenSSLConan()
              print('✅ conanfile.py is valid')
          except Exception as e:
              print(f'❌ conanfile.py validation failed: {e}')
              import traceback
              traceback.print_exc()
              exit(1)
          "
          
      - name: Module Import Check
        run: |
          echo "Testing module imports..."
          python3 -c "
          import sys
          sys.path.insert(0, '.')
          
          # Test essential modules
          try:
              from openssl_tools.util.custom_logging import setup_logging_from_config
              print('✅ openssl_tools.util.custom_logging - OK')
          except ImportError as e:
              print(f'❌ openssl_tools.util.custom_logging - FAILED: {e}')
              sys.exit(1)
              
          try:
              sys.path.insert(0, './scripts/conan')
              from conan_functions import get_default_conan
              print('✅ scripts.conan.conan_functions - OK')
          except ImportError as e:
              print(f'❌ scripts.conan.conan_functions - FAILED: {e}')
              sys.exit(1)
          "
          
      - name: Quick Conan Test
        run: |
          echo "Running quick Conan test..."
          conan profile detect --force
          conan config show
          echo "✅ Conan basic configuration works"
          
      - name: Report Fast Check Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Fast validation passed - PR is ready for comprehensive testing"
          else
            echo "❌ Fast validation failed - blocking PR merge"
          fi
