# .github/workflows/quality-gates.yml
name: Core Quality Gates
on:
  workflow_call:
    inputs:
      artifact-path:
        required: true
        type: string
    secrets:
      inherits: inherit  # Core secret pass [web:27]

jobs:
  core-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Core Artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - name: Core Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'artifacts/'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'  # Core block [file:36]
      - name: Upload Core SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'