name: Test Simple

on:
  workflow_dispatch:
  push:
    branches: [ simplify-openssl-build ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test successful"