name: Trigger OpenSSL Integration Tests

on:
    push:
        branches: [main, master]
        paths:
            - "conanfile.py"
            - "VERSION.dat"
    workflow_dispatch:
        inputs:
            openssl_repo:
                description: "OpenSSL repo to trigger (owner/repo format)"
                required: false
                default: "sparesparrow/openssl"

jobs:
    trigger-openssl:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger OpenSSL repository dispatch
              run: |
                  curl -X POST \
                    -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
                    -H "Accept: application/vnd.github.v3+json" \
                    https://api.github.com/repos/${{ github.event.inputs.openssl_repo || 'sparesparrow/openssl' }}/dispatches \
                    -d '{"event_type": "openssl-tools-updated", "client_payload": {"tools_version": "1.2.0", "trigger_repo": "${{ github.repository }}"}}'
