# Copyright 2022-2025 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Windows Compression GitHub CI

on:
  pull_request:
    paths:
      - 'crypto/comp/*.c'
      - '.github/workflows/windows_comp.yml'
  push:
    paths:
      - '**.c'

permissions:
  contents: read

jobs:
  zstd:
    runs-on: windows-latest
    env:
      CONAN_USER_HOME: ${{ github.workspace }}/.conan2
      CONAN_COLOR_DISPLAY: 1
      CLICOLOR_FORCE: 1
      CLICOLOR: 1
    steps:
    - uses: actions/checkout@v4
    - name: checkout fuzz/corpora submodule
      run: git submodule update --init --depth 1 fuzz/corpora
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Set up Conan Python Environment
      run: |
        python scripts/setup-ci-environment.py
    
    - name: Create Conan build profile
      run: |
        conan profile detect --force
    
    - name: Conan install
      run: |
        conan install . --profile=conan-dev/profiles/windows-msvc2022.profile -o enable_zstd=True -o fips=True
    
    - name: Conan build
      run: |
        conan build . --profile=conan-dev/profiles/windows-msvc2022.profile -o enable_zstd=True -o fips=True
    
    - name: Conan test
      timeout-minutes: 60
      run: |
        conan test . --profile=conan-dev/profiles/windows-msvc2022.profile -o enable_zstd=True -o fips=True

  brotli:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: checkout fuzz/corpora submodule
      run: git submodule update --init --depth 1 fuzz/corpora
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Set up Conan Python Environment
      run: |
        python scripts/setup-ci-environment.py
    
    - name: Create Conan build profile
      run: |
        conan profile detect --force
    
    - name: Conan install
      run: |
        conan install . --profile=conan-dev/profiles/windows-msvc2022.profile -o enable_brotli=True -o fips=True
    
    - name: Conan build
      run: |
        conan build . --profile=conan-dev/profiles/windows-msvc2022.profile -o enable_brotli=True -o fips=True
    
    - name: Conan test
      timeout-minutes: 60
      run: |
        conan test . --profile=conan-dev/profiles/windows-msvc2022.profile -o enable_brotli=True -o fips=True
