# Copyright 2021-2025 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Windows GitHub CI

on: [pull_request, push]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shared:
    # Run a job for each of the specified target architectures:
    strategy:
      max-parallel: 1
      matrix:
        platform:
          - arch: amd64
            os: windows-2022
            profile: windows-msvc2022
            conan_options: -o fips=True -o enable_lms=True -o enable_demos=True
          - arch: amd64
            os: windows-2025
            profile: windows-msvc2022
            conan_options: -o fips=True -o enable_lms=True -o no_thread_pool=True -o no_quic=True
          - arch: x86
            os: windows-2022
            profile: windows-msvc2022-x86
            conan_options: -o fips=False -o enable_lms=True -o no_deprecated=True
    runs-on: ${{ matrix.platform.os }}
    env:
      CONAN_USER_HOME: ${{ github.workspace }}/.conan2
      CONAN_COLOR_DISPLAY: 1
      CLICOLOR_FORCE: 1
      CLICOLOR: 1
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Set up Conan Python Environment
      run: |
        python scripts/setup-ci-environment.py
    
    - name: Conan install
      run: |
        conan install . --profile=conan-dev/profiles/${{ matrix.platform.profile }}.profile ${{ matrix.platform.conan_options }}
    
    - name: Conan build
      run: |
        conan build . --profile=conan-dev/profiles/${{ matrix.platform.profile }}.profile ${{ matrix.platform.conan_options }}
    - name: download coreinfo
      if: github.event_name != 'pull_request'
      run: |
        mkdir _build\coreinfo
        Invoke-WebRequest -Uri "https://download.sysinternals.com/files/Coreinfo.zip" -outfile "_build\coreinfo\Coreinfo.zip"
    - name: Gather openssl version info
      working-directory: _build
      run: |
        apps/openssl.exe version -v
        apps/openssl.exe version -v | %{($_ -split '\s+')[1]}
        apps/openssl.exe version -v | %{($_ -split '\s+')[1] -replace '([0-9]+\.[0-9]+)(\..*)','$1'}
        echo "OSSL_VERSION=$(apps/openssl.exe version -v | %{($_ -split '\s+')[1] -replace '([0-9]+\.[0-9]+)(\..*)','$1'})" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Set registry keys
      working-directory: _build
      run: |
        echo ${Env:OSSL_VERSION}
        reg.exe add HKLM\SOFTWARE\OpenSSL-${Env:OSSL_VERSION}-openssl /v OPENSSLDIR /t REG_EXPAND_SZ /d TESTOPENSSLDIR /reg:32
        reg.exe add HKLM\SOFTWARE\OpenSSL-${Env:OSSL_VERSION}-openssl /v ENGINESDIR /t REG_EXPAND_SZ /d TESTOPENSSLDIR /reg:32
        reg.exe add HKLM\SOFTWARE\OpenSSL-${Env:OSSL_VERSION}-openssl /v MODULESDIR /t REG_EXPAND_SZ /d TESTOPENSSLDIR /reg:32
        reg.exe query HKLM\SOFTWARE\OpenSSL-${Env:OSSL_VERSION}-openssl /v OPENSSLDIR /reg:32
    - name: get cpu info
      working-directory: _build
      continue-on-error: true
      run: |
        7z.exe x coreinfo/Coreinfo.zip
        ./Coreinfo64.exe -accepteula -f
        ./apps/openssl.exe version -c
    - name: Check platform symbol usage
      working-directory: _build
      run: perl ../util/checkplatformsyms.pl ../util/platform_symbols/windows-symbols.txt libcrypto-3-x64.dll ./libssl-3-x64.dll
    - name: Conan test
      timeout-minutes: 60
      run: |
        conan test . --profile=conan-dev/profiles/${{ matrix.platform.profile }}.profile ${{ matrix.platform.conan_options }}
    - name: install
      # Run on 64 bit only as 32 bit is slow enough already
      if: ${{ matrix.platform.arch == 'amd64' }}
      working-directory: _build
      shell: cmd
      run: |
        call "${{ matrix.platform.vcvars }}"
        mkdir _dest
        nmake install DESTDIR=_dest

  plain:
    runs-on: windows-2022
    env:
      CONAN_USER_HOME: ${{ github.workspace }}/.conan2
      CONAN_COLOR_DISPLAY: 1
      CLICOLOR_FORCE: 1
      CLICOLOR: 1
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Set up Conan Python Environment
      run: |
        python scripts/setup-ci-environment.py
    
    - name: Conan install
      run: |
        conan install . --profile=conan-dev/profiles/windows-msvc2022.profile -o fips=False -o enable_demos=True -o no_shared=True -o enable_md2=True -o enable_rc5=True -o enable_ssl3=True -o enable_ssl3_method=True -o enable_weak_ssl_ciphers=True -o enable_trace=True -o enable_crypto_mdebug=True
    
    - name: Conan build
      run: |
        conan build . --profile=conan-dev/profiles/windows-msvc2022.profile -o fips=False -o enable_demos=True -o no_shared=True -o enable_md2=True -o enable_rc5=True -o enable_ssl3=True -o enable_ssl3_method=True -o enable_weak_ssl_ciphers=True -o enable_trace=True -o enable_crypto_mdebug=True
    - name: download coreinfo
      run: |
        mkdir _build\coreinfo
        Invoke-WebRequest -Uri "https://download.sysinternals.com/files/Coreinfo.zip" -outfile "_build\coreinfo\Coreinfo.zip"
    - name: get cpu info
      working-directory: _build
      continue-on-error: true
      run: |
        7z.exe x coreinfo/Coreinfo.zip
        ./Coreinfo64.exe -accepteula -f
        ./apps/openssl.exe version -c
    - name: Conan test
      timeout-minutes: 60
      run: |
        conan test . --profile=conan-dev/profiles/windows-msvc2022.profile -o fips=False -o enable_demos=True -o no_shared=True -o enable_md2=True -o enable_rc5=True -o enable_ssl3=True -o enable_ssl3_method=True -o enable_weak_ssl_ciphers=True -o enable_trace=True -o enable_crypto_mdebug=True

  minimal:
    runs-on: windows-2022
    env:
      CONAN_USER_HOME: ${{ github.workspace }}/.conan2
      CONAN_COLOR_DISPLAY: 1
      CLICOLOR_FORCE: 1
      CLICOLOR: 1
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Set up Conan Python Environment
      run: |
        python scripts/setup-ci-environment.py
    
    - name: Conan install
      run: |
        conan install . --profile=conan-dev/profiles/windows-msvc2022.profile -o fips=False -o enable_demos=True -o no_bulk=True -o no_deprecated=True -o no_asm=True -o no_threads=True -o no_shared=True
    
    - name: Conan build
      run: |
        conan build . --profile=conan-dev/profiles/windows-msvc2022.profile -o fips=False -o enable_demos=True -o no_bulk=True -o no_deprecated=True -o no_asm=True -o no_threads=True -o no_shared=True
    - name: download coreinfo
      run: |
        mkdir _build\coreinfo
        Invoke-WebRequest -Uri "https://download.sysinternals.com/files/Coreinfo.zip" -outfile "_build\coreinfo\Coreinfo.zip"
    - name: get cpu info
      working-directory: _build
      continue-on-error: true
      run: |
        7z.exe x coreinfo/Coreinfo.zip
        ./Coreinfo64.exe -accepteula -f
        ./apps/openssl.exe version -c
    - name: Conan test
      timeout-minutes: 60
      run: |
        conan test . --profile=conan-dev/profiles/windows-msvc2022.profile -o fips=False -o enable_demos=True -o no_bulk=True -o no_deprecated=True -o no_asm=True -o no_threads=True -o no_shared=True

  cygwin:
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        os:
          - windows-2022
        platform:
          - arch: win64
            config: -DCMAKE_C_COMPILER=gcc --strict-warnings enable-demos no-fips
# are we really learning sth new from win32? So let's save some CO2 for now disabling this
#          - arch: win32
#            config: -DCMAKE_C_COMPILER=gcc --strict-warnings no-fips
    runs-on: ${{ matrix.os }}
    env:
      CYGWIN_NOWINPATH: 1
      SHELLOPTS: igncr
# Don't overwhelm github CI VMs:
      MAKE_PARAMS: -j 4
    steps:
# Checkout before cygwin can mess with PATH...
    - uses: actions/checkout@v4
    - uses: cygwin/cygwin-install-action@f61179d72284ceddc397ed07ddb444d82bf9e559 #v5
      with:
         packages: perl git make gcc-core
    - name: Check repo
      run: cygcheck -V
    - name: Full cygcheck status
      run: cygcheck -s -v -r -h
# Activate this if checkout action fails:
#    - name: Clone repo
#      run: bash -c "pwd && git clone --branch ${{ github.ref_name }} --depth 1 https://github.com/${{ github.repository }}.git"
    - name: Full build
      run: bash -c "gcc --version && ./config ${{ matrix.platform.config }} && make $MAKE_PARAMS"
# Disable testing for now. TBD: Need local cygwin installation to debug .
#    - name: Run openssl tests
#      run: bash -c "cd openssl && make V=1 test"
